spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devdb
    username: root
    password: Madu7788?
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

---
environment: test
server:
    port: 4000
myCustomVarTree:
  welcomeMsg: Hello from Test

---
environment: prod
server:
  port: 5000
myCustomVarTree:
  welcomeMsg: Hello form Prod
